# Traffic tracker for AHRQ GitHub repositories

name: traffic tracker

# Controls when the workflow will run
on:
  # should run every hour
  schedule:
    - cron: "0 6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python github_api_traffic.py

      - name: Commit changes
        run: |
          git config --global user.email "mitcheem@gmail.com"
          git config --global user.name "Emily Mitchell"
          git add .
          git commit -m "Add generated CSV traffic files"
          git push
